# Use the official Python image
FROM python:3.10

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    ffmpeg \
    libpq-dev \
    libxml2-dev \
    libxslt1-dev \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy and install dependencies
# COPY requirements.txt /app/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
# COPY . /app/
COPY . .

# Expose the port
EXPOSE 8000

RUN python manage.py collectstatic --noinput

# Run the Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# For Production
# CMD ["gunicorn", "--workers=3", "--bind=0.0.0.0:8000", "Course.wsgi:application"]